version: '3.8'
services:
  redis:
    image: redis:6.0-alpine
    container_name: "shipment-service"
    restart: always
    environment:
      - REDIS_PASSWORD=sertton
    ports:
      - '3000:3000'